### ISSUE TITLE
您好，只重写了分类任务，有没有重写分割的code

### ISSUE THREAD

**Issue by wfs123456** [eat-slim/PointNeXt_pure_python#1]
您好，只重写了分类任务，有重写分割的code吗

**Comment by eat-slim** [comment]
模型配置字典的'type'值设置为'segmentation'就是分割模型

**Comment by wfs123456** [comment]
明白了，感谢回复，方便可以更新一个依赖的requirements.txt吗

**Comment by eat-slim** [comment]
> 明白了，感谢回复，方便可以更新一个依赖的requirements.txt吗

已更新
